Implemented visual staking border on chunks
angushtlam/embarker pull request #4
Opened 2020-04-12 06:42 UTC by angushtlam

2020-04-12 07:32 UTC, nenofite requested changes

2020-04-12 07:32 UTC, nenofite commented on src/main/java/com/raeic/embarker/land/schedulers/LandScheduler.java
> +                    Method PlayerConnection_sendPacket = PlayerConnection.getMethod("sendPacket", Packet);
pls move reflection out of loop

2020-04-12 07:32 UTC, nenofite commented on src/main/java/com/raeic/embarker/land/schedulers/LandScheduler.java
> +                    e.printStackTrace();
I would prefer to catch these during plugin initialization and throw as an error, rather than a warning

2020-04-12 09:30 UTC, angushtlam commented on src/main/java/com/raeic/embarker/land/schedulers/LandScheduler.java
> +            System.out.println("[Embarker] Reflections are not working for LandScheduler. Visual staking borders are disabled.");
Initialization checks are made here

2020-04-13 02:42 UTC, nenofite approved these changes

2020-04-13 06:43 UTC, merged